### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by sweatpotato13** [sweatpotato13/secp256r1-crypto#1]
## 🚀 Proposal Detail

**Describe the solution you'd like**

- [ ] validation check for private key
- [ ] generate key pair
- [ ] sign / verify (ECDSA)
- [ ] encrypt / decrypt (ECIES with AES-256-CBC)
- [ ] ECDH

## Reference
[eccrypto](https://github.com/bitchan/eccrypto)
[secp256r1](https://github.com/xiawu/secp256r1-node)
